export type IntentEvents =
  | 'Set Project'
  | 'Load Dataset'
  | 'Change Dataset'
  | 'Add Plot'
  | 'Prediction Selection'
  | 'Point Selection'
  | 'Change Category'
  | 'Toggle Category'
  | 'Add Brush'
  | 'Remove Brush'
  | 'Update Brush'
  | 'Change Brush Type'
  | 'Filter'
  | 'Aggregate'
  | 'Label';
